import {
  ALL_COLOR_MAPPINGS,
  PLACEABLE_COLOR_MAPPINGS,
  UNPLACEABLE_COLOR_MAPPINGS,
  VISITABLE_COLOR_MAPPINGS,
} from "./constants";

export type CellId = {
  y: number;
  x: number;
};

export type ALL_COLOR_MAPPINGS_TYPE =
  typeof ALL_COLOR_MAPPINGS[keyof typeof ALL_COLOR_MAPPINGS];
export type PLACEABLE_COLOR_MAPPINGS_TYPE =
  typeof PLACEABLE_COLOR_MAPPINGS[keyof typeof PLACEABLE_COLOR_MAPPINGS];
export type UNPLACEABLE_COLOR_MAPPINGS_TYPE =
  typeof UNPLACEABLE_COLOR_MAPPINGS[keyof typeof UNPLACEABLE_COLOR_MAPPINGS];
export type VISITABLE_COLOR_MAPPINGS =
  typeof VISITABLE_COLOR_MAPPINGS[keyof typeof VISITABLE_COLOR_MAPPINGS];
